version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
